version : '3.9'

services:

  fastapi:
    build:
      context: ./app/python/
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    volumes:
      - ./app/code/:/app/
    ports:
      - "8000:8000"
    networks: 
        - data-network

  nginx_project:
    image: nginx:alpine
    container_name: nginx_project
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./app/code/static/:/app/static/
    networks:
      - data-network

networks:
  data-network:
    driver: bridge